### ISSUE TITLE
code synthesis

### ISSUE THREAD

**Issue by Wen1163204547** [LaVi-Lab/CLEVA#2]
The comments in the prompt of code synthesis have an extra space on each line, which causes the human_eval to fail the code format check after concatenating the string with completion.

**Comment by Jianqiao-Zhao** [comment]
Hi @Wen1163204547 , thank you for the information! We are double-checking the data you mentioned. I think the comment format does not affect human_eval performance much. Maybe you can get around it temporarily as well. We will give you further feedback once our re-examination is finished

**Comment by lyy1994** [comment]
@Wen1163204547 We have done checking the code synthesis data. Indeed, there are a few prompts that have some issues due to the annotations and the resulting flawed data preprocessing. We have fixed those problems and released the new data. Please check and let us know if there are any other issues. Thanks!
